In [1]:
import pandas as pd
from pathlib import Path

In [2]:
dir_path = Path.cwd().parents[2]

data_folder = dir_path.joinpath("data/ibis/raw_manually_sorted")

df_path = data_folder.joinpath("Cement.xlsx")

export_path = dir_path.joinpath("data/ibis/interim/Cement.csv")

In [3]:
df = pd.read_excel(df_path)
df

,Company Name,AddCode,Add1,Add2,City,Pincode,Taluk,District,State,Tel,Fax,Email,Names,Capacity,Units,Upcoming Capacity,Units.1,Captive Power Plant Capacity
0,Aadi Cements Pvt Ltd,Branch Office,"Valsana Road, Opp. College",NaN,Panol,383430.0,Idar,Sabarkantha,Gujarat,Tel: 0-76000 52020,Fax: 079-26873408,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aadi Cements Pvt Ltd,Plant,"Block No. 22, Bakarpura",Idar Taluk,Bakarpura,NaN,Idar,Sabarkantha,Gujarat,Tel: 02778-250318 / 250319,NaN,NaN,NaN,0.1,mtpa,NaN,NaN,NaN
2,Abhaya Cements Pvt Ltd,Plant,Nadikudi,Dachepalli,Nadikudi,522414.0,Dachepalle,Guntur,Andhra Pradesh,Tel: 0-9246222199,NaN,Email: abhayacements@yahoo.in,NaN,NaN,NaN,132,tpd,NaN
3,Absolute Cement & Polymers Pvt Ltd,Plant,"Plot No. 6/7, Udairampur","Nangla, Dhaulana Tehsil",Dhaulana,NaN,Hapur,Ghaziabad,Uttar Pradesh,Tel: 0-98376 26318 /0-99350 55590,NaN,NaN,NaN,NaN,NaN,0.6,mtpa,NaN
4,Abu Industries Ltd,Plant,Labad Village,NaN,Labad,NaN,NaN,Dhar,Madhya Pradesh,Tel: 0-99260-09545,NaN,NaN,NaN,9000.0,tpa,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673,Zaffron Enterprises Pvt Ltd,Plant,Village Khonmoh,Srinagar,Srinagar,191104.0,NaN,Srinagar,Jammu & Kashmir,NaN,NaN,NaN,NaN,NaN,NaN,200,tpd,NaN
674,Zuari Cements Ltd,Plant,Solapur Grinding Unit,"Auj Village,",Auj,413221.0,NaN,Solapur,Maharashtra,Tel: 0217-2500750,NaN,Email: deepak.kakkar@zcltd.com,"Deepak Kakkar, (0-94154 12000) (deepak.kakkar@...",NaN,NaN,NaN,NaN,NaN
675,Zuari Cements Ltd,Plant,"Krishna Nagar, Yerraguntla,","Dist. â€“ Kadapa,",Yerraguntla,516309.0,Prodattur,Cuddapah,Andhra Pradesh,Tel: 08563 - 275102 / 275107 / 275108 / 275195,Fax: 275195,Email: zclygl@zcltd.com,"GNB Rao, Sr. Vice President (gnb.rao@zcltd.com)",4.6,mtpa,NaN,NaN,NaN
676,Zuari Cements Ltd,Plant,P O Dondapadu (Formerly Shree Vishnu Cements),Sitapuram,Donda Padu,508246.0,Mellacheruvu,Nalagonda,Telangana,Tel: 8683235232 / 8683235107,Fax: 08683 - 235229,Email: svclspm@zcltd.com,"K Papa Rao, Plant Head, (k.paparao@zcltd.com) ...",1.4,mtpa,NaN,NaN,6 MW
677,Zuari Cements Ltd,Plant,Chennai Grinding Unit,"Ambedkar Street, Athipattu",Chennai,600120.0,NaN,Tiruvallur,Tamil Nadu,Tel: 044-27960027,Fax: 27960028,Email: zclgu@zcltd.com,"Ramesh Babu SP, Asst.Gen.Mgr(Production), (p.r...",1.0,mtpa,NaN,NaN,NaN

In [4]:
df.columns

Index(['Company Name', 'AddCode', 'Add1', 'Add2', 'City', 'Pincode', 'Taluk',
       'District', 'State', 'Tel', 'Fax', 'Email', 'Names', 'Capacity',
       'Units', 'Upcoming Capacity', 'Units.1',
       'Captive Power Plant Capacity'],
      dtype='object')

### Filtering Plants

In [5]:
df['AddCode'].unique()

array(['Branch Office', 'Plant', 'Corp Office', 'Registered Office',
       'Project Office', 'Head Office', 'Site', 'Regional Office',
       'Marketing Office', 'HO/Corp Office', 'Site Office', nan],
      dtype=object)

In [6]:
df = df[df['AddCode']=='Plant']
df.drop('AddCode',axis=1, inplace=True)

/tmp/ipykernel_25098/1743636810.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('AddCode',axis=1, inplace=True)

### Check Duplicates

In [7]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [Company Name, Add1, Add2, City, Pincode, Taluk, District, State, Tel, Fax, Email, Names, Capacity, Units, Upcoming Capacity, Units.1, Captive Power Plant Capacity]
Index: []

In [8]:
isid_cols = ['Company Name', 'Pincode', 'Add1', 'Add2']


df[df.duplicated(isid_cols,keep=False)]

,Company Name,Add1,Add2,City,Pincode,Taluk,District,State,Tel,Fax,Email,Names,Capacity,Units,Upcoming Capacity,Units.1,Captive Power Plant Capacity
517,Shree Gopal Concrete Pvt Ltd,Shreegopal House,"Rambagan, Raniganj",Durgapur,733121.0,NaN,Dakshin Dinajpur,West Bengal,Tel: 0341 3267708,Fax: 0341 3267708,Email: sgpl151@rediffmail.com,NaN,500.0,tpd,NaN,NaN,NaN
518,Shree Gopal Concrete Pvt Ltd,Shreegopal House,"Rambagan, Raniganj",Durgapur,733121.0,NaN,Dakshin Dinajpur,West Bengal,Tel: 0341 3267708,Fax: 0341 3267708,Email: sgpl151@rediffmail.com,NaN,300.0,tpd,NaN,NaN,NaN

### Cleaning Column names and Columns

In [9]:
cols = df.columns

cols = [x.replace(" ", "_").lower() for x in cols]

cols

['company_name',
 'add1',
 'add2',
 'city',
 'pincode',
 'taluk',
 'district',
 'state',
 'tel',
 'fax',
 'email',
 'names',
 'capacity',
 'units',
 'upcoming_capacity',
 'units.1',
 'captive_power_plant_capacity']

In [10]:
df.columns = cols

df.rename(columns={
    "units.1":"upcoming_capacity_unit"
}, inplace=True)

/tmp/ipykernel_25098/461494988.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={

In [11]:
df.drop(['tel',
 'fax',
 'email',
 'names',
 'captive_power_plant_capacity'], axis=1, inplace=True)

/tmp/ipykernel_25098/3798550352.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(['tel',

In [12]:
df

,company_name,add1,add2,city,pincode,taluk,district,state,capacity,units,upcoming_capacity,upcoming_capacity_unit
1,Aadi Cements Pvt Ltd,"Block No. 22, Bakarpura",Idar Taluk,Bakarpura,NaN,Idar,Sabarkantha,Gujarat,0.1,mtpa,NaN,NaN
2,Abhaya Cements Pvt Ltd,Nadikudi,Dachepalli,Nadikudi,522414.0,Dachepalle,Guntur,Andhra Pradesh,NaN,NaN,132,tpd
3,Absolute Cement & Polymers Pvt Ltd,"Plot No. 6/7, Udairampur","Nangla, Dhaulana Tehsil",Dhaulana,NaN,Hapur,Ghaziabad,Uttar Pradesh,NaN,NaN,0.6,mtpa
4,Abu Industries Ltd,Labad Village,NaN,Labad,NaN,NaN,Dhar,Madhya Pradesh,9000.0,tpa,NaN,NaN
6,ACC Ltd,Sindri Cement Works (Grinding Unit),"P.O. ACC Colony,",Dhanbad,828124.0,NaN,NaN,Jharkhand,2.5,mtpa,2.0,mtpa
...,...,...,...,...,...,...,...,...,...,...,...,...
673,Zaffron Enterprises Pvt Ltd,Village Khonmoh,Srinagar,Srinagar,191104.0,NaN,Srinagar,Jammu & Kashmir,NaN,NaN,200,tpd
674,Zuari Cements Ltd,Solapur Grinding Unit,"Auj Village,",Auj,413221.0,NaN,Solapur,Maharashtra,NaN,NaN,NaN,NaN
675,Zuari Cements Ltd,"Krishna Nagar, Yerraguntla,","Dist. â€“ Kadapa,",Yerraguntla,516309.0,Prodattur,Cuddapah,Andhra Pradesh,4.6,mtpa,NaN,NaN
676,Zuari Cements Ltd,P O Dondapadu (Formerly Shree Vishnu Cements),Sitapuram,Donda Padu,508246.0,Mellacheruvu,Nalagonda,Telangana,1.4,mtpa,NaN,NaN
677,Zuari Cements Ltd,Chennai Grinding Unit,"Ambedkar Street, Athipattu",Chennai,600120.0,NaN,Tiruvallur,Tamil Nadu,1.0,mtpa,NaN,NaN

In [13]:
df.to_csv(export_path, index=False)