In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

In [3]:
dir_path = Path.cwd().parents[2]

data_folder = dir_path.joinpath("data/ibis/raw_manually_sorted")

df_path = data_folder.joinpath("Pharma.xlsx")

export_path = dir_path.joinpath("data/ibis/interim/Pharma.csv")

In [4]:
df = pd.read_excel(df_path)
df

,Company Name,AddCode,Add1,Add2,CityPost,Pincode,Taluk,District,State,Tel,Fax,Email,Names,Capacity,Units,UpCpy,UpCpyUnits,Captive Power Plant Capacity
0,A Choksey Chemical Industries,Plant,"8-A.Udhana, Udyognagar,","P.B.No.19,Udhana,",Surat,395007.0,NaN,Surat,Gujarat,Tel: 0261 - 2278546,Fax: 0261 - 2278345,Email: achoksey_surat@yahoo.co.in,NaN,NaN,NaN,NaN,NaN,NaN
1,A D Pharmachem Pvt Ltd,Plant,Plot No. A-86 MIDC,Paithan,Paithan,431148.0,NaN,Aurangabad,Maharashtra,0240-2552212 /2333 622,NaN,adpharmachem@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN
2,A G Bio Systems Pvt Ltd,Plant,"Plot No. 35-E, APIIC Industrial Estate","Phase V, Cherlapally",Hyderabad,500051.0,NaN,Rangareddy,Telangana,Tel: 040-29806787,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A J Organica Pvt Ltd,Plant,"288, Raisoni Industrial Estate,","Hinjawadi Phase 2, Mann",Hinjawadi,411057.0,Mulshi,Pune,Maharashtra,Tel: 0-90116 99898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A K Biotech Pvt Ltd,Plant,"EPIP Kartholi, SIDCO Industrial Complex,",Bari Brahmana,Bari Brahmna,181133.0,NaN,Jammu,Jammu & Kashmir,Tel: 9596781715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3527,Zyden Gentec Ltd,Plant,"Sy. No. 168, IDA Bollaram,","Jinnaram Mandal, Medak District",Bollaram,502325.0,NaN,Medak,Telangana,Tel: 040-27845404/9912781800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3528,Zydus Cadila Healthcare Ltd,Plant,P-203 to 213 Kundaim,"Industrial Area,",Kundaim,403115.0,NaN,South Goa,Goa,0832-6615124 / 6615400-01,NaN,upen.shah@zyduscadila.com,NaN,NaN,NaN,NaN,NaN,NaN
3529,Zydus Cadila Ltd,Plant,"A-2 MIDC Patalganga Taluka,","Khalapur, Dist. Raigad,",Khalapur,410203.0,Khalapur,Raigad,Maharashtra,02146-251215,NaN,admin@konkanindustrialpublications.com,NaN,NaN,NaN,NaN,NaN,NaN
3530,Zydus Takeda Healthcare Pvt Ltd,Plant,"C-4. TTC MIDC Industrial Area,","Thane Belapur Road, Pawne,",Navi Mumbai,400705.0,NaN,Thane,Maharashtra,022-27682666,NaN,Sunil.Desai@zydustakeda.com,NaN,NaN,NaN,NaN,NaN,NaN
3531,Zyg Pharma Ltd,Plant,"Plot No.- 810, Sector â€“ III, Industrial Area",Pithampur,Pithampur,454775.0,NaN,Dhar,Madhya Pradesh,Tel: 07292-256224 / 256449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.columns

Index(['Company Name', 'AddCode', 'Add1', 'Add2', 'CityPost', 'Pincode',
       'Taluk', 'District', 'State', 'Tel', 'Fax', 'Email', 'Names',
       'Capacity', 'Units', 'UpCpy', 'UpCpyUnits',
       'Captive Power Plant Capacity'],
      dtype='object')

### Filtering Plants

In [6]:
df['AddCode'].unique()

array(['Plant', 'Branch Office', 'Corp Office', 'Unit II', 'Head Office',
       'R&D Center', 'R&D Centre', 'Registered Office', 'Site',
       'HO/Corp Office', nan], dtype=object)

In [7]:
df[df['AddCode'].isin(['Unit II'])]

,Company Name,AddCode,Add1,Add2,CityPost,Pincode,Taluk,District,State,Tel,Fax,Email,Names,Capacity,Units,UpCpy,UpCpyUnits,Captive Power Plant Capacity
117,Afflatus Pharmaceuticals Pvt Ltd,Unit II,"Killa No-6/21/1(5-7), Village Joshi Jaat Roar,","Bahalgarh, Sonipat,",Bahalgarh,131021.0,NaN,Sonipat,Haryana,NaN,NaN,Email: info@afflatuspharma.in,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df = df[df['AddCode'].isin(['Plant', 'Unit II'])]
df.drop('AddCode',axis=1, inplace=True)

/tmp/ipykernel_235804/202367064.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('AddCode',axis=1, inplace=True)

### Check Duplicates

In [9]:
df[df.duplicated(keep=False)]

,Company Name,Add1,Add2,CityPost,Pincode,Taluk,District,State,Tel,Fax,Email,Names,Capacity,Units,UpCpy,UpCpyUnits,Captive Power Plant Capacity
636,Burnet Pharmaceuticals Pvt Ltd,"28/5, C.N.Roy Road,",3rd Floor,Kolkatta,700039.0,NaN,NaN,West Bengal,033-40121919 / 23452419 / 25 / 26 / 28,033-23452423,burnet@vsnl.com,NaN,NaN,NaN,NaN,NaN,NaN
639,Burnet Pharmaceuticals Pvt Ltd,"28/5, C.N.Roy Road,",3rd Floor,Kolkatta,700039.0,NaN,NaN,West Bengal,033-40121919 / 23452419 / 25 / 26 / 28,033-23452423,burnet@vsnl.com,NaN,NaN,NaN,NaN,NaN,NaN
2122,Novel Nutrients Pvt Ltd,"Sy. No 902, 903/1, 904/1A Krishnama Kothoor Vi...",Kamandoddi Post,Kamandoddi,635109.0,NaN,Krishnagiri,Tamil Nadu,080 2325 3578/96 2017 7557,080 2325 3578,mail@novelnutrient.com,NaN,NaN,NaN,NaN,NaN,NaN
2125,Novel Nutrients Pvt Ltd,"Sy. No 902, 903/1, 904/1A Krishnama Kothoor Vi...",Kamandoddi Post,Kamandoddi,635109.0,NaN,Krishnagiri,Tamil Nadu,080 2325 3578/96 2017 7557,080 2325 3578,mail@novelnutrient.com,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
isid_cols = ['Company Name', 'Pincode', 'Add1', 'Add2']


df[df.duplicated(isid_cols,keep=False)]

,Company Name,Add1,Add2,CityPost,Pincode,Taluk,District,State,Tel,Fax,Email,Names,Capacity,Units,UpCpy,UpCpyUnits,Captive Power Plant Capacity
636,Burnet Pharmaceuticals Pvt Ltd,"28/5, C.N.Roy Road,",3rd Floor,Kolkatta,700039.0,NaN,NaN,West Bengal,033-40121919 / 23452419 / 25 / 26 / 28,033-23452423,burnet@vsnl.com,NaN,NaN,NaN,NaN,NaN,NaN
639,Burnet Pharmaceuticals Pvt Ltd,"28/5, C.N.Roy Road,",3rd Floor,Kolkatta,700039.0,NaN,NaN,West Bengal,033-40121919 / 23452419 / 25 / 26 / 28,033-23452423,burnet@vsnl.com,NaN,NaN,NaN,NaN,NaN,NaN
1258,Gulshan Polyols Ltd,"Plot No.10, 11 & 9, Boregaon Industrial Area,","Tehsil Sausar,",Boregaon,NaN,Sausar,Chhindwara,Madhya Pradesh,Tel: 07165-226020,NaN,Email: marketingindus@gulshanindia.com,NaN,NaN,NaN,500.0,klpd,15 MW (U)
1259,Gulshan Polyols Ltd,"Plot No.10, 11 & 9, Boregaon Industrial Area,","Tehsil Sausar,",Boregaon,NaN,Sausar,Chhindwara,Madhya Pradesh,Tel: 07165-226020,NaN,Email: marketingindus@gulshanindia.com,NaN,NaN,NaN,NaN,NaN,3 MW (U)
1803,Mahi Polymers,"A/4, Yogeshwar Park Society","Opp: Ratnaba Schools, Thakkar Nagar",Ahmedabad,380001.0,NaN,Ahmedabad,Gujarat,Tel: 9925037276 / 9925142545,NaN,Email: hasmukhpatel8805@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN
1804,Mahi Polymers,"A/4, Yogeshwar Park Society","Opp: Ratnaba Schools, Thakkar Nagar",Ahmedabad,380001.0,NaN,Ahmedabad,Gujarat,Tel: 9925142545,NaN,Email: hasmukhpatel8805@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN
2122,Novel Nutrients Pvt Ltd,"Sy. No 902, 903/1, 904/1A Krishnama Kothoor Vi...",Kamandoddi Post,Kamandoddi,635109.0,NaN,Krishnagiri,Tamil Nadu,080 2325 3578/96 2017 7557,080 2325 3578,mail@novelnutrient.com,NaN,NaN,NaN,NaN,NaN,NaN
2125,Novel Nutrients Pvt Ltd,"Sy. No 902, 903/1, 904/1A Krishnama Kothoor Vi...",Kamandoddi Post,Kamandoddi,635109.0,NaN,Krishnagiri,Tamil Nadu,080 2325 3578/96 2017 7557,080 2325 3578,mail@novelnutrient.com,NaN,NaN,NaN,NaN,NaN,NaN
2484,Regenix Drugs Ltd,"A-2, SIDCO Pharmaceutical Complex,","Alathur,",Alathur,603110.0,NaN,Kanchipuram,Tamil Nadu,Tel: 044-2744 4410,NaN,Email: info@regenix.in,NaN,NaN,NaN,NaN,NaN,NaN
2485,Regenix Drugs Ltd,"A-2, SIDCO Pharmaceutical Complex,","Alathur,",Alathur,603110.0,NaN,Kanchipuram,Tamil Nadu,Tel: 044 - 27444410,NaN,Email: info@regenix.in,NaN,NaN,NaN,NaN,NaN,NaN
3019,Supreem Pharmaceuticals Mysore Pvt Ltd,"#73, 74 & 48P-1, KIADB Industrial Area,",Nanjangud,Nanjangud,571302.0,NaN,Mysore,Karnataka,"08221-224484, 91/94498 13468",NaN,info@supreempharma.in,NaN,NaN,NaN,NaN,NaN,NaN
3020,Supreem Pharmaceuticals Mysore Pvt Ltd,"#73, 74 & 48P-1, KIADB Industrial Area,",Nanjangud,Nanjangud,571302.0,NaN,Mysore,Karnataka,"Tel: 08221-224483, 84 /99000 43495",NaN,Email: info@supreempharma.in,NaN,NaN,NaN,NaN,NaN,NaN
3238,Uni Labs India Pvt Ltd,"No.124, Poonamallee High Road,",Velappanchavadi,Chennai,600077.0,NaN,Chennai,Tamil Nadu,044 - 65425838,NaN,unilabsindia@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN
3240,Uni Labs India Pvt Ltd,"No.124, Poonamallee High Road,",Velappanchavadi,Chennai,600077.0,NaN,Chennai,Tamil Nadu,044 - 65425838,NaN,Email: unilabsindia@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN

### Cleaning Column names and Columns

In [11]:
cols = df.columns

cols = [x.replace(" ", "_").lower() for x in cols]

cols

['company_name',
 'add1',
 'add2',
 'citypost',
 'pincode',
 'taluk',
 'district',
 'state',
 'tel',
 'fax',
 'email',
 'names',
 'capacity',
 'units',
 'upcpy',
 'upcpyunits',
 'captive_power_plant_capacity']

In [12]:
df.columns = cols

df.rename(columns={
    
   "units":"unit",
   "units.1":"upcoming_capacity_unit",
   "upcpy":'upcoming_capacity',
   'upcpyunits':'upcoming_capacity_units',
   'citypost':'city'
   
}, inplace=True)

/tmp/ipykernel_235804/73261851.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={

In [13]:
df.drop(['tel',
 'fax',
 'email',
 'names',
 'captive_power_plant_capacity'], axis=1, inplace=True)

/tmp/ipykernel_235804/3798550352.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(['tel',

In [14]:
df

,company_name,add1,add2,city,pincode,taluk,district,state,capacity,unit,upcoming_capacity,upcoming_capacity_units
0,A Choksey Chemical Industries,"8-A.Udhana, Udyognagar,","P.B.No.19,Udhana,",Surat,395007.0,NaN,Surat,Gujarat,NaN,NaN,NaN,NaN
1,A D Pharmachem Pvt Ltd,Plot No. A-86 MIDC,Paithan,Paithan,431148.0,NaN,Aurangabad,Maharashtra,NaN,NaN,NaN,NaN
2,A G Bio Systems Pvt Ltd,"Plot No. 35-E, APIIC Industrial Estate","Phase V, Cherlapally",Hyderabad,500051.0,NaN,Rangareddy,Telangana,NaN,NaN,NaN,NaN
3,A J Organica Pvt Ltd,"288, Raisoni Industrial Estate,","Hinjawadi Phase 2, Mann",Hinjawadi,411057.0,Mulshi,Pune,Maharashtra,NaN,NaN,NaN,NaN
4,A K Biotech Pvt Ltd,"EPIP Kartholi, SIDCO Industrial Complex,",Bari Brahmana,Bari Brahmna,181133.0,NaN,Jammu,Jammu & Kashmir,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3527,Zyden Gentec Ltd,"Sy. No. 168, IDA Bollaram,","Jinnaram Mandal, Medak District",Bollaram,502325.0,NaN,Medak,Telangana,NaN,NaN,NaN,NaN
3528,Zydus Cadila Healthcare Ltd,P-203 to 213 Kundaim,"Industrial Area,",Kundaim,403115.0,NaN,South Goa,Goa,NaN,NaN,NaN,NaN
3529,Zydus Cadila Ltd,"A-2 MIDC Patalganga Taluka,","Khalapur, Dist. Raigad,",Khalapur,410203.0,Khalapur,Raigad,Maharashtra,NaN,NaN,NaN,NaN
3530,Zydus Takeda Healthcare Pvt Ltd,"C-4. TTC MIDC Industrial Area,","Thane Belapur Road, Pawne,",Navi Mumbai,400705.0,NaN,Thane,Maharashtra,NaN,NaN,NaN,NaN
3531,Zyg Pharma Ltd,"Plot No.- 810, Sector â€“ III, Industrial Area",Pithampur,Pithampur,454775.0,NaN,Dhar,Madhya Pradesh,NaN,NaN,NaN,NaN

In [15]:
df.to_csv(export_path, index=False)